pipeline:
  build:
    group: build
    image: gradle:jdk11
    commands:
      - gradle build
  publish:
    group: publish
    image: plugins/docker
    repo: hpareek07/sample_gradle_project
    tags:
      - "${DRONE_TAG}"
      - "latest"
    when:
      branch:
        - master
    secrets: [ ci_user, ci-pass ]
